document.write('<body>');
document.write('   ');
document.write('   <meta name="viewport" content="width=device-width, initial-scale=0.86, maximum-scale=5.0, minimum-scale=0.86">');
document.write('   ');
document.write('   <div class="stop"> ');
document.write('   ');
document.write('   <center>');
document.write('      <div class="centre">');
document.write('      <img src="https://media.discordapp.net/attachments/1123004262432112772/1142249451558285412/pikayut8.png">');
document.write('      ');
document.write('      ');
document.write('   ');
document.write('   <br><br><br><br><br>');
document.write('   ');
document.write('   <h3>');
document.write('   <p><?xml version="1.0" encoding="utf-8"?><!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->');
document.write('<svg width="64px" height="64px" viewBox="-2.64 -2.64 29.28 29.28" fill="none" xmlns="http://www.w3.org/2000/svg" transform="matrix(1, 0, 0, 1, 0, 0)rotate(0)"><g id="SVGRepo_bgCarrier" stroke-width="0" transform="translate(0,0), scale(1)"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round" stroke="#000000" stroke-width="0.096"></g><g id="SVGRepo_iconCarrier"> <path d="M3 13.6493C3 16.6044 5.41766 19 8.4 19L16.5 19C18.9853 19 21 16.9839 21 14.4969C21 12.6503 19.8893 10.9449 18.3 10.25C18.1317 7.32251 15.684 5 12.6893 5C10.3514 5 8.34694 6.48637 7.5 8.5C4.8 8.9375 3 11.2001 3 13.6493Z" stroke="#000000" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"></path> </g></svg>');
document.write(' <br>Maintenance générale </p>');
document.write('   </center></h3>');
document.write('   </div>');
document.write('</div>');
document.write('');
document.write('</body>');
document.write('<style>');
document.write('   ');
document.write('   .svg {');
document.write('      10px');
document.write('   }');
document.write('   .centre {');
document.write('   position:absolute;');
document.write('      top:20%;');
document.write('      bottom:50%;');
document.write('   }');
document.write('   ');
document.write('   ');
document.write('   ');
document.write('   ');
document.write('   img{');
document.write('   ');
document.write('   width: 55%;');
document.write('   border-radius:35%;');
document.write('   ');
document.write('   }');
document.write('   ');
document.write('   body{');
document.write('      background : #363838;');
document.write('      color : white;');
document.write('   }');
document.write('   ');
document.write('   .stop { ');
document.write('      ');
document.write('      position : absolute;');
document.write('      top: 0px;');
document.write('      left : 0px;');
document.write('      right: 0px;');
document.write('      bottom: 0px;');
document.write('     ');
document.write('     ');
document.write('   }');
document.write('</style>');
document.write('');
               
